version: "2"

services:
  sessions:
    restart: always
    image: redis:latest
  redis:
    restart: always
    image: redis:latest

  mysql:
    image: percona:5.7
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2

  php7fpm:
    build: ./env/fpm7/
    restart: always
    volumes:
     - /srv:/srv
     - /tmp:/tmp
    links:
     - mysql:mysql
     - redis:redis
     - sessions:sessions
    networks:
      main:
        aliases:
          - php7fpm

  nginx:
    restart: always
    image: nginx:latest
    volumes:
    - ./env/nginx.conf.d:/etc/nginx/conf.d
    - ./env/nginx.certs:/etc/nginx/certs
    - /srv:/srv
    - /tmp:/tmp
    dns:
    - 77.88.8.8
    networks:
      main:
        aliases:
          - nginx
  
  gateway:
    restart: always
    image: million12/varnish:latest
    ports:
    - 80:80/tcp    
    networks:
      main:
        aliases:
          - gateway

networks:
  main:
